# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.admin.site:
        class: AppBundle\Admin\SiteAdmin
        arguments: [~, AppBundle\Entity\Site, AppBundle:SiteAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Site}

    app.admin.page:
        class: AppBundle\Admin\PageAdmin
        arguments: [~, AppBundle\Entity\Page, AppBundle:PageAdmin]
        tags:
            - {name: sonata.admin, manager_type: orm, group: admin, label: Page}