imports:
    - { resource: '@SonataTranslationBundle/Resources/config/config.yml'}

sonata_translation:
    locales: [en, ru]
    default_locale: ru
    # here enable the types you need
    gedmo:
        enabled: true
    phpcr:
        enabled: true